version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: "exit 0"
  
  web:
    build: .
    container_name: docker_django
    command: >
      sh -c "python manage.py makemigrations app &&
             python manage.py migrate app &&
             python manage.py search_index --rebuild -f &&
             python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/ code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    
volumes:
  postgres-data:
  esdata:
    driver: local