# Generated by Django 4.0.5 on 2022-08-06 11:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import rocrate.rocrate


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_crate'), ('app', '0003_alter_crate_regkeywords'), ('app', '0004_delete_car'), ('app', '0005_crate_regauthor_alter_crate_reglicense'), ('app', '0006_rename_regauthor_crate_author_and_more'), ('app', '0007_cratejson'), ('app', '0008_entityjson'), ('app', '0009_alter_cratejson_id_alter_entityjson_id'), ('app', '0010_alter_cratejson_id'), ('app', '0011_dataentity_delete_cratejson_delete_entityjson_and_more'), ('app', '0012_alter_dataentity_description'), ('app', '0013_rename_dataentity_entity'), ('app', '0014_alter_entity_crate'), ('app', '0015_person_remove_crate_author_id_and_more'), ('app', '0016_alter_crate_datepublished_alter_entity_datecreated_and_more'), ('app', '0017_alter_crate_keywords'), ('app', '0018_citation_organization_remove_crate_citation_name_and_more'), ('app', '0019_alter_crate_identifier'), ('app', '0020_people_delete_person_alter_crate_authors'), ('app', '0021_person_alter_crate_authors'), ('app', '0022_delete_person_alter_crate_authors'), ('app', '0023_rename_dicipline_crate_discipline'), ('app', '0024_alter_crate_discipline'), ('app', '0025_crate_profile_crate_profileid')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Crate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('datePublished', models.DateTimeField()),
                ('license', models.CharField(blank=True, max_length=128, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('dicipline', models.CharField(blank=True, max_length=128, null=True)),
                ('identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('authors', models.ManyToManyField(related_name='crates', to='app.person')),
            ],
            bases=(models.Model, rocrate.rocrate.ROCrate),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=8)),
                ('dateCreated', models.DateTimeField(blank=True, null=True)),
                ('dateModified', models.DateTimeField(blank=True, null=True)),
                ('programmingLanguage', models.CharField(blank=True, max_length=128, null=True)),
                ('crate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='app.crate')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='crate',
            name='publisher',
            field=models.ManyToManyField(related_name='crates', to='app.organization'),
        ),
        migrations.AddField(
            model_name='crate',
            name='citation',
            field=models.ManyToManyField(related_name='crates', to='app.citation'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='identifier',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocrid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('ocrid', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='crate',
            name='authors',
            field=models.ManyToManyField(related_name='crates', to='app.people'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='crate',
            name='authors',
            field=models.ManyToManyField(related_name='crates', to='app.person'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='crate',
            name='authors',
            field=models.ManyToManyField(related_name='crates', to='app.people'),
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='dicipline',
            new_name='discipline',
        ),
        migrations.AlterField(
            model_name='crate',
            name='discipline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='crate',
            name='profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='profileID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
