# Generated by Django 4.0.5 on 2022-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='regKeywords',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
