# Generated by Django 4.0.5 on 2022-06-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_crate_regkeywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
