# Generated by Django 4.0.5 on 2022-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='crate',
            name='regAuthor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='crate',
            name='regLicense',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
