# Generated by Django 4.0.5 on 2022-06-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_crate_regauthor_alter_crate_reglicense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crate',
            old_name='regAuthor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='regDatePublished',
            new_name='datePublished',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='regDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='regKeywords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='regLicense',
            new_name='license',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='regName',
            new_name='name',
        ),
    ]
