# Generated by Django 4.0.5 on 2022-06-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_regauthor_crate_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrateJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
    ]
