# Generated by Django 4.0.5 on 2022-06-20 15:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cratejson_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=8)),
                ('dateCreated', models.DateField(blank=True, null=True)),
                ('dateModified', models.DateField(blank=True, null=True)),
                ('programmingLanguage', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CrateJson',
        ),
        migrations.DeleteModel(
            name='EntityJson',
        ),
        migrations.RemoveField(
            model_name='crate',
            name='author',
        ),
        migrations.AddField(
            model_name='crate',
            name='author_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='author_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='citation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='citation_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='dicipline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='identifier',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='publisher_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='crate',
            name='license',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dataentity',
            name='crate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crate'),
        ),
    ]
