# Generated by Django 4.0.5 on 2022-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dataentity_delete_cratejson_delete_entityjson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
