# Generated by Django 4.0.5 on 2022-06-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_dataentity_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEntity',
            new_name='Entity',
        ),
    ]
