# Generated by Django 4.0.5 on 2022-06-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_dataentity_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='crate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='app.crate'),
        ),
    ]
