# Generated by Django 4.0.5 on 2022-06-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_entity_crate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='crate',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='crate',
            name='author_name',
        ),
        migrations.AddField(
            model_name='crate',
            name='authors',
            field=models.ManyToManyField(related_name='crates', to='app.person'),
        ),
    ]
