# Generated by Django 4.0.5 on 2022-07-08 21:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_crate_datepublished_alter_entity_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
    ]
