# Generated by Django 4.0.5 on 2022-07-11 15:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_citation_organization_remove_crate_citation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='identifier',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), blank=True, null=True, size=None),
        ),
    ]
