# Generated by Django 4.0.5 on 2022-07-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_crate_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocrid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('ocrid', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='crate',
            name='authors',
            field=models.ManyToManyField(related_name='crates', to='app.people'),
        ),
    ]
