# Generated by Django 4.0.5 on 2022-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_people_delete_person_alter_crate_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='crate',
            name='authors',
            field=models.ManyToManyField(related_name='crates', to='app.person'),
        ),
    ]
