# Generated by Django 4.0.5 on 2022-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_person_alter_crate_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='crate',
            name='authors',
            field=models.ManyToManyField(related_name='crates', to='app.people'),
        ),
    ]
