# Generated by Django 4.0.5 on 2022-07-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_person_alter_crate_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crate',
            old_name='dicipline',
            new_name='discipline',
        ),
    ]
