# Generated by Django 4.0.5 on 2022-07-20 13:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_dicipline_crate_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='discipline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
    ]
