# Generated by Django 4.0.5 on 2022-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_crate_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='crate',
            name='profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='crate',
            name='profileID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
